name: codestyle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==0.12.17
        poetry config settings.virtualenvs.create false
        poetry run pip install -U setuptools
        poetry install
    - name: Check codestyle
      run: |
        PYTHONPATH=. python scripts/verify.py --checks flake8
        PYTHONPATH=. python scripts/verify.py --checks mypy
        PYTHONPATH=. python scripts/verify.py --checks black
    - name: Test with pytest
      run: PYTHONPATH=. python scripts/verify.py --checks pytest
    - name: Download test dataset
      run: |
        mkdir -p ./data/test
        wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=18bZdW3nVn_fa6dVmSMGlLMXx6dPy6_cb' \
          -O test_data.zip
        unzip -qqo test_data.zip -d ./data/test
    - name: Create dataset
      run: |
        PYTHONPATH=. python scripts/create_dataset.py \
          --csv_path ./data/test/test.csv \
          --col_name comment_text \
          --output_dir ./data/test/ \
          --num_dissimilar 5000 \
          --num_similar 5000 \
          --test_size 0.2
    - name: Check pipeline
      run: |
        python train.py \
          --model_dir ./experiment \
          --data_dir ./data/test \
          --num_epochs 2 \
          --batch_size 64 \
          --patience 1