name: codestyle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config settings.virtualenvs.create false
        poetry run pip install -U setuptools
        poetry install
    - name: Check codestyle
      run: |
        PYTHONPATH=. python scripts/verify.py --checks flake8
        PYTHONPATH=. python scripts/verify.py --checks mypy
        PYTHONPATH=. python scripts/verify.py --checks black
    - name: Test with pytest
      run: PYTHONPATH=. python scripts/verify.py --checks pytest
