name: core_check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==0.12.17
        poetry config settings.virtualenvs.create false
        poetry run pip install -U setuptools
        poetry install
    - name: Check codestyle
      run: |
        PYTHONPATH=. python scripts/verify.py --checks flake8
        PYTHONPATH=. python scripts/verify.py --checks mypy
        PYTHONPATH=. python scripts/verify.py --checks black
    - name: Test with pytest
      run: PYTHONPATH=. python scripts/verify.py --checks pytest
    - name: Check training
      run: |
        export GPU_ID="-1"
        export TRAIN_DATA_PATH="./tests/fixtures/data/train.jsonl"
        export VALID_DATA_PATH="./tests/fixtures/data/valid.jsonl"

        allennlp train ./training_config/cnn.jsonnet \
            --serialization-dir ./logs/test \
            --include-package deeplev